// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// binit3
NumericVector binit3(NumericVector x1s, NumericVector y1s, NumericVector x2s, NumericVector y2s, int nbins, double r, int do_auto);
RcppExport SEXP _drp_binit3(SEXP x1sSEXP, SEXP y1sSEXP, SEXP x2sSEXP, SEXP y2sSEXP, SEXP nbinsSEXP, SEXP rSEXP, SEXP do_autoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1s(x1sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1s(y1sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2s(x2sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2s(y2sSEXP);
    Rcpp::traits::input_parameter< int >::type nbins(nbinsSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type do_auto(do_autoSEXP);
    rcpp_result_gen = Rcpp::wrap(binit3(x1s, y1s, x2s, y2s, nbins, r, do_auto));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_drp_binit3", (DL_FUNC) &_drp_binit3, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_drp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
