# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do the binning of the cross-correlation
#'
#' @param x1s Vector of x coordinates for type 1 cells
#' @param y1s Vector of y coordinates for type 1 cells
#' @param x2s Vector of x coordinates for type 2 cells
#' @param y2s Vector of y coordinates for type 2 cells
#' @param nbins Number of bins
#' @param r Bin width
#' @param do_auto Set to TRUE for auto-correlation
#' @export
binit3 <- function(x1s, y1s, x2s, y2s, nbins, r, do_auto) {
    .Call('_drp_binit3', PACKAGE = 'drp', x1s, y1s, x2s, y2s, nbins, r, do_auto)
}

